// Plain-language definitions. Any element with data-term="key" shows the definition on hover or focus.

export const GLOSSARY = {
  decision_model: { term: 'Decision model', def: 'A model that never writes text. You give it a situation and a set of possible answers, and it returns how likely each answer is. Also called a System One model.' },
  system_one: { term: 'System One', def: 'Borrowed from psychology (Kahneman): fast, intuitive judgement, as opposed to slow step-by-step reasoning (System Two). These models make quick judgement calls; they do not think out loud.' },
  state: { term: 'State (the situation)', def: 'What you want judged: an email, a support ticket, a log line, a product review, or a JSON object describing what is going on. The API calls it the state. The model reads it once and answers every question about it.' },
  question: { term: 'Question', def: 'One judgement you want made about the situation. Each question has a type, a sentence saying what you want to know, and the allowed answers.' },
  choice: { term: 'Pick one', def: 'Pick exactly one option from a list you define, like which team should handle a ticket. You get a probability for every option. The API type is "choice".' },
  score: { term: 'Rate on a scale', def: 'Place the situation on an ordered scale you define (2 to 10 levels), like how urgent something is. You get the probability of each level plus an average position that can land between levels. The API type is "score".' },
  noul: { term: 'Yes or no', def: 'Is a statement true? You get the probability of yes. TypeSafe calls this type "noul".' },
  multi: { term: 'Pick any', def: 'Tick every option that applies, like which topics a message mentions. Each option gets its own yes/no probability, and options above your threshold are selected. A studio extension; it is built from yes/no questions.' },
  rank: { term: 'Put in order', def: 'Order the options from most to least likely, like which problem to fix first. A studio extension built on a pick-one question.' },
  number: { term: 'Estimate a number', def: 'Estimate a quantity from a set of numbers you list, like how many days until a customer leaves. You get a best estimate plus an 80% range. A studio extension built on a scale question.' },
  criteria: { term: 'Criteria', def: 'The allowed answers for a question. For pick one, a name for each option plus an optional description the model reads. For a scale, the ordered levels.' },
  probability: { term: 'Probability', def: 'How much of the model\'s belief goes to an answer, from 0% to 100%. All options of a pick-one question add up to 100%.' },
  confidence: { term: 'Confidence', def: 'How far the answer is from a coin toss. 0 means the model cannot tell the options apart; 1 means all its belief is on one answer. Computed with TypeSafe\'s formula so every model is comparable.' },
  calibration: { term: 'Calibration', def: 'Whether the percentages can be taken at face value. A well-calibrated model that says 80% is right about 80% of the time. Accuracy and calibration are different: a model can be right often yet overconfident.' },
  temperature: { term: 'Calibration temperature', def: 'One number that stretches or squeezes the probabilities without changing which answer wins. Above 1 makes the model sound less sure; below 1 more sure. Fitting it on about 100 of your own labelled examples is the standard way to fix overconfidence.' },
  threshold: { term: 'Act threshold', def: 'Your rule for when to trust the model: if its top answer is at least this likely, act automatically; otherwise send it to a person or a bigger model. This is called confidence gating.' },
  finetune: { term: 'Fine-tuned model', def: 'A model taught your own decisions on the Train page: the original model plus a small file of changes learned from your examples. It is only kept if it did better than the original on examples it never saw, without getting worse at general decisions.' },
  gating: { term: 'Confidence gating', def: 'Acting on confident answers automatically and escalating unsure ones. It is the main way decision models are used in real software.' },
  cascade: { term: 'Cascade', def: 'Use a fast, cheap decision model first; only when it is unsure, ask a slower, more expensive model or a human. Most traffic never needs the expensive step.' },
  one_pass: { term: 'One forward pass', def: 'The model reads the situation once and computes every answer in a single run through the network, instead of writing an answer word by word. That is why it takes milliseconds.' },
  token: { term: 'Token', def: 'The unit models read text in: roughly three quarters of a word. Context limits and speed are measured in tokens.' },
  context: { term: 'Context length', def: 'The most text (in tokens) a model can read at once. Longer inputs are rejected or cut off, depending on the model.' },
  parameters: { term: 'Parameters', def: 'The learned numbers inside a model. More parameters usually means more knowledge and better judgement, but more memory and slower answers.' },
  lora: { term: 'LoRA adapter', def: 'A small add-on trained on top of a frozen base model. Kev and Lev are LoRA adapters: you download the small adapter plus the base model it attaches to.' },
  base_model: { term: 'Base model', def: 'The general-purpose model an adapter is built on, like Qwen3.5-4B. It is downloaded once and shared by every adapter that uses it.' },
  encoder: { term: 'Encoder', def: 'A model that reads text in both directions at once (like BERT). Small, fast, and good at classification. Laya, Julia and GLiNER are encoders.' },
  unified_memory: { term: 'Unified memory', def: 'On computers like Apple Silicon Macs and the NVIDIA GB10, the CPU and GPU share one pool of memory. Every loaded model uses part of it; ejecting a model gives it back.' },
  eject: { term: 'Eject', def: 'Unload a model from memory. Its files stay on disk, so loading it again is quick.' },
  multimodal: { term: 'Multimodal', def: 'Able to take more than text: images, audio or video. Here, Intern-Decision reads images and Jev-Omni reads images, audio and video.' },
  order_bias: { term: 'Option-order bias', def: 'Some models give different answers when the same options are listed in a different order. The order test shuffles your options to check whether the answer holds.' },
  latency: { term: 'Latency', def: 'How long the model took to answer, measured inside the model process. The first request after loading can be slower while the model warms up.' },
  jev: { term: 'Jev', def: 'The first commercial System One model, released by TypeSafe AI in September 2026. It is only available as a paid API; every model in this studio is an open alternative you run yourself.' },
  typesafe_api: { term: 'TypeSafe API', def: 'The request format Jev introduced: POST /v1/systemone with a state and named questions. This studio speaks the same format, so code written for Jev works here by changing the base URL.' },
  act_gate: { term: 'Built-in act gate', def: 'Laya models have a second output that estimates how safe it is to act on the answer automatically. It is separate from the answer probabilities.' },
  request_id: { term: 'Request id', def: 'A unique id for each call, returned in the x-typesafe-request-id header, exactly as TypeSafe does. Useful for matching logs.' },
  extensions: { term: 'Studio extensions', def: 'Extra answer fields (decision, top probability, latency) and the pick any, put in order and estimate a number types. Official SDKs ignore them; send the header X-Basal-Extensions: 1 to receive the extra fields.' },
};
